name: Deploy localdev
on:
  pull_request:
  workflow_dispatch:
jobs:
  deploy-localdev:
    uses: LibriVox/librivox-ansible/.github/workflows/localdev.yaml@master
    with:
      catalog_git_refpsec: ${{ github.ref }}
      catalog_git_version: ${{ github.sha }}
      playbooks_repo: LibriVox/librivox-ansible
      playbooks_repo_ref: master
